import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["src/global.css"],
    outDir: "dist",
  },
  {
    dts: true,
    entry: [
      "src/theme",
      "src/translate",
      "src/model",
      "src/client",
      "src/server",
      "src/utils",
      "src/config"
    ],
    format: ["esm"],
    minify: true,
    target: "esnext",
    outDir: "dist",
    splitting: true,
    external: ["react", "react-dom"],
    tsconfig: "./tsconfig.json",
    bundle: true,
  },
  {
    dts: true,
    entry: ["src/legacy/views"],
    format: ["esm"],
    minify: true,
    target: "esnext",
    outDir: "dist/legacy/views",
    splitting: true,
    external: ["react", "react-dom"],
    tsconfig: "./tsconfig.json",
    bundle: true,
  },
  {
    dts: true,
    entry: ["src/legacy"],
    format: ["esm"],
    minify: true,
    target: "esnext",
    outDir: "dist/legacy",
    splitting: true,
    external: ["react", "react-dom"],
    tsconfig: "./tsconfig.json",
    bundle: true,
  },
  {
    dts: true,
    entry: ["src/components/ui"],
    format: ["esm"],
    minify: true,
    target: "esnext",
    outDir: "dist/components/base",
    splitting: true,
    external: ["react", "react-dom"],
    tsconfig: "./tsconfig.json",
    bundle: true,
  },
  {
    dts: true,
    entry: ["src/components/icons"],
    format: ["esm"],
    minify: true,
    target: "esnext",
    outDir: "dist/components/icons",
    splitting: true,
    external: ["react", "react-dom"],
    tsconfig: "./tsconfig.json",
    bundle: true,
  },
]);
