import { defineConfig } from "tsup";

export default defineConfig([
    // CSS files
    {
        entry: ["src/global.css"],
        outDir: "dist/",
    },
    {
        entry: ["src/lib/tour.css"],
        outDir: "dist/lib",
    },
    // Lib folder
    {
        dts: true,
        entry: ["src/lib"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/lib",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // Store folder
    {
        dts: true,
        entry: ["src/store"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/store",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // Views folder
    {
        dts: true,
        entry: ["src/views"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/views",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // Hooks folder
    {
        dts: true,
        entry: ["src/hooks"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/hooks",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // UI Components
    {
        dts: true,
        entry: ["src/components/ui"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/ui",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // Icons
    {
        dts: true,
        entry: ["src/components/icons"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/icons",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
    // Blocks
    {
        dts: true,
        entry: ["src/components/blocks"],
        format: ["esm", "cjs"],
        minify: true,
        target: "esnext",
        outDir: "dist/blocks",
        splitting: true,
        external: [
            "react",
            "next/link",
            "next/image",
            "next/server",
            "formik",
            "yup",
        ],
        tsconfig: "./tsconfig.json",
        bundle: true,
        cjsInterop: true,
    },
]);
